from pydantic import BaseModel, Field

class StockTechnicalIndicators(BaseModel):
    date: str = Field(description="The date of the stock data")
    open: float = Field(description="The opening price of the stock")
    high: float = Field(description="The highest price of the stock")
    low: float = Field(description="The lowest price of the stock")
    close: float = Field(description="The closing price of the stock")
    volume: int = Field(description="The volume of the stock")
    macd: float = Field(description="The MACD value")
    macd_histogram: float = Field(description="The MACD Histogram value")
    macd_signal: float = Field(description="The MACD Signal value")
    n_high: float = Field(description="The highest price in the last 14 days")
    n_low: float = Field(description="The lowest price in the last 14 days")
    K: float = Field(description="The %K value for the Stochastics")
    D: float = Field(description="The %D value for the Stochastics")
    rsi: float = Field(description="The Relative Strength Index value")
    dr: float = Field(description="The daily range of the stock")
    adr: float = Field(description="The average daily range of the stock")
    ma_50: float = Field(description="The 50-day moving average of the stock")
    ma_200: float = Field(description="The 200-day moving average of the stock")
    death_cross_signal: float = Field(description="The death cross signal value")
    death_cross: float = Field(description="The death cross value")
    golden_cross_signal: float = Field(description="The golden cross signal value")
    golden_cross: float = Field(description="The golden cross value")
    obv: float = Field(description="The On-Balance Volume value")